site_name: Religions of the Ancient Mediterranean
theme_dir: theme
site_url: https://ram.readthedocs.io
site_description: Coursebook for DH1 Hacking History, at USF
site_author: David J. Thomas
copyright: 'Copyright &copy; 2017 <a href="mailto:dave.a.base@gmail.com">David J. Thomas</a>'
repo_url: https://github.com/thePortus/his4936-ram-course-workbook.git
repo_name: 'GitHub'
pages:
- Home: index.md
- Lessons: lessons.md
- Project: project.md
